// =========================
// Multiplayer protocol types
// =========================
// Shared between the browser client (roomClient/host/guest) and the relay
// server. The server only uses the connection-management messages
// (create/join/leave/lock/relay); the game payload types are used by clients.

import { TileKind } from "../game/assets/blocks";
import { PowerupType } from "../game/assets/powerups";
import { PlayerStats } from "../game/hooks/tracker";
import { Direction } from "./game";

// =========================
// Room / roster
// =========================

/** A participant in a room, as reported by the relay server. */
export interface RoomPlayer {
  slot: number;
  name: string;
  isHost: boolean;
}

/** A spectator in a room. Spectators watch the game but take no slot. */
export interface RoomSpectator {
  name: string;
}

/** How a slot in the local roster is controlled. */
export type ControlKind = "local" | "remote" | "computer";

/** A slot in the host-built roster used to initialize the game. */
export interface RosterEntry {
  id: string;
  name: string;
  control: ControlKind;
  slot: number;
}

// =========================
// Server <-> client connection messages
// =========================

export type ClientToServerMessage =
  | { t: "create"; name: string }
  | { t: "join"; code: string; name: string }
  | { t: "spectate"; code: string; name: string }
  | { t: "leave" }
  | { t: "lock" }
  | { t: "relay"; to: "host" | "guests"; payload: GamePayload };

export type ServerToClientMessage =
  | { t: "created"; code: string; slot: number }
  | { t: "joined"; code: string; slot: number }
  | { t: "spectating"; code: string }
  | { t: "room"; code: string; players: RoomPlayer[]; spectators: RoomSpectator[] }
  | { t: "error"; message: string }
  | { t: "hostLeft" }
  /** Sent to the host when a spectator joins a locked (in-progress) room. */
  | { t: "spectatorJoined" }
  | { t: "relay"; from: number; payload: GamePayload };

// =========================
// Game payloads (relayed between host and guests)
// =========================

/** Per-player input state, sent by guests to the host every change. */
export interface InputPayload {
  t: "input";
  sequence: number;
  up: boolean;
  down: boolean;
  left: boolean;
  right: boolean;
  bomb: boolean;
  /** One discrete movement generated by one physical key press. */
  move?: Direction;
}

/** Host-to-guest latency probe. */
export interface LatencyPingPayload {
  t: "latencyPing";
  id: number;
  slot: number;
}

export interface LatencyPongPayload {
  t: "latencyPong";
  id: number;
}

/** A single cell's mutable state in a snapshot. */
export interface CellSnapshot {
  /** Index of the cell in the grid (row * gridCols + col). */
  index: number;
  tile: TileKind;
  bomb: boolean;
  powerup: PowerupType | null;
}

/** A character's mutable state in a snapshot. */
export interface CharacterSnapshot {
  id: string;
  /** Highest guest input sequence processed by the host for this player. */
  lastProcessedInputSequence?: number;
  row: number;
  col: number;
  facing: Direction;
  lives: number;
  winning: boolean;
  isImmune: boolean;
  isWalking: boolean;
  isHurt: boolean;
  hasShield: boolean;
  isShieldBlock: boolean;
  isShieldExpiring: boolean;
}

/** Full authoritative state of the game at one instant, host -> guests. */
export interface SnapshotPayload {
  t: "snapshot";
  characters: CharacterSnapshot[];
  stats: PlayerStats[];
  cells: CellSnapshot[];
  timeElapsedMs: number;
}

/** Sent once by the host when the game starts, so guests can build the grid. */
export interface StartPayload {
  t: "start";
  cellTypes: TileKind[];
  roster: RosterEntry[];
}

/** Transient blast event relayed by the host for guest visuals/sound. */
export interface BlastPayload {
  t: "blast";
  cells: { row: number; col: number }[];
  reach: { up: number; down: number; left: number; right: number };
  cellSizePx: number;
}

/** Sent by the host when the game ends so guests can show the end screen. */
export interface GameOverPayload {
  t: "gameOver";
  state: "GAME_OVER" | "WIN";
  winner?: PlayerStats;
  gameStats: import("../game/hooks/tracker").GameStats;
}

export type GamePayload =
  | InputPayload
  | SnapshotPayload
  | StartPayload
  | BlastPayload
  | GameOverPayload
  | LatencyPingPayload
  | LatencyPongPayload;
